#!/bin/sh

# create user & set pswd

export COLUMNS LINES
#cursor underline    
# echo -e "\e[4 q"

pkg update && pkg upgrade
mkdir ~/{desk,dox,dl,music,templates,pub,pix,vids,code,imp} 

cp -r ~/myTermux/{.colorscheme,.config,.local,.termux,.zshrc,.zprofile} ~/
chmod +x ~/.local/bin/scripts/*

pkg install -y man bc x11-repo \
proot root-repo tsu \
fd bat exa tree ripgrep \
mpd ncmpcpp mpv cava \
ffmpeg imagemagick termimage \
zip unrar tar lf \
axel wget rsync openssh \
htop ncdu procs \
tmux zsh fzf \
rxfetch cowsay termux-api inotify-tools \
neovim clang nodejs ccls shfmt shellcheck stylua 
# dnsutils php android-tools qit xclip

# Packer install
git clone --depth 1 https://github.com/wbthomason/packer.nvim \
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.config/zsh/zsh-syntax-highlighting 
git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.config/zsh/zsh-autosuggestions

 
